package com.unbound.core.content

import com.unbound.core.model.Appearance
import com.unbound.core.model.CharacterTemplate

/**
 * Starting points, not archetypes to be filled in. Each has a concrete problem already in motion,
 * because a character who wants nothing gives the world nothing to push against.
 *
 * The player may take one as-is, edit any field, write their own, or ask the model to invent one.
 */
object Characters {

    val ALL: List<CharacterTemplate> = listOf(
        CharacterTemplate(
            id = "smuggler",
            name = "Rook Vance",
            age = 31,
            gender = "man",
            tagline = "Owes money to people who do not write things down.",
            appearance = Appearance(
                summary = "Lean, weather-worn, dark cropped hair going grey at the temples, a broken nose that set badly.",
                face = "angular, broken nose, three-day stubble",
                skin = "olive, wind-burned",
                hair = "black, cropped short, greying at the temples",
                eyes = "dark brown",
                build = "lean and wiry",
                scars = listOf("burn across the left forearm"),
                clothing = "salt-stained oilskin coat over a patched wool shirt",
                signatureEquipment = listOf("a short gutting knife", "a ring of keys that fit nothing he owns"),
            ),
            personality = "Charming when it is useful, silent when it is not. Keeps promises he is paid to keep.",
            desires = "To clear the debt and buy a boat nobody else has a claim on.",
            fears = "Being held somewhere he cannot leave.",
            skills = listOf("reading people", "small boats", "moving cargo quietly", "knife work"),
            weaknesses = listOf("cannot resist a bet", "known to the harbour watch"),
            background = "Ran cargo for the docks for eleven years. Lost a shipment that was not his to lose.",
            goals = listOf("Pay off 400 crowns before the month turns"),
            secrets = listOf("He knows who actually took the missing shipment, and it was a friend."),
            startingCurrency = 42,
        ),
        CharacterTemplate(
            id = "knight",
            name = "Ser Aldis Marren",
            age = 44,
            gender = "woman",
            tagline = "Stripped of rank for a killing she will not explain.",
            appearance = Appearance(
                summary = "Tall, broad-shouldered, iron-grey hair shorn close, a long scar from ear to collarbone.",
                face = "square jaw, heavy brow, a long white scar from left ear to collarbone",
                skin = "pale, freckled",
                hair = "iron-grey, shorn close to the skull",
                eyes = "pale green",
                build = "tall and heavy through the shoulders",
                scars = listOf("ear to collarbone, left side"),
                clothing = "a good coat gone shabby, no insignia where insignia used to be",
                signatureEquipment = listOf("a longsword with the crest filed off"),
            ),
            personality = "Formal, direct, slow to anger and frightening when angry. Hates being thanked.",
            desires = "To be useful again without being owned again.",
            fears = "That she was right to do it.",
            skills = listOf("sword and shield", "command", "reading a fight before it starts"),
            weaknesses = listOf("bad knee", "physically incapable of lying well"),
            background = "Twenty years sworn. Killed a superior officer in front of witnesses and said nothing at the trial.",
            goals = listOf("Find honest work that does not require a name"),
            secrets = listOf("The officer she killed was about to have a village burned."),
            startingCurrency = 15,
        ),
        CharacterTemplate(
            id = "conartist",
            name = "Lisenne Fay",
            age = 27,
            gender = "woman",
            tagline = "Six names, four of them still solvent.",
            appearance = Appearance(
                summary = "Small, quick, copper hair pinned up, expensive clothes that do not quite fit.",
                face = "round, freckled, a practised open smile",
                skin = "fair, freckled",
                hair = "copper, pinned up with cheap silver",
                eyes = "grey-green",
                build = "small and quick",
                clothing = "a fine merchant's jacket taken in badly at the shoulders",
                signatureEquipment = listOf("a sealed letter of credit that is not hers"),
            ),
            personality = "Talks first, thinks while talking. Genuinely likes people she is robbing.",
            desires = "One score large enough to stop.",
            fears = "Being recognised in the wrong room.",
            skills = listOf("lying", "forgery", "reading a room", "picking locks"),
            weaknesses = listOf("cannot fight at all", "sentimental about people who trust her"),
            background = "Raised in a counting house, learned the paperwork, left with some of it.",
            goals = listOf("Convert the stolen letter of credit before it is reported"),
            secrets = listOf("One of her marks was her brother, and he has not stopped looking."),
            startingCurrency = 120,
        ),
        CharacterTemplate(
            id = "healer",
            name = "Odo Wren",
            age = 38,
            gender = "man",
            tagline = "Treats everyone, which has made him enemies on both sides.",
            appearance = Appearance(
                summary = "Stooped, careful hands, thinning sandy hair, an apron that has seen worse days.",
                face = "long, tired, deep lines at the mouth",
                skin = "sallow",
                hair = "sandy, thinning",
                eyes = "hazel",
                build = "stooped, thin",
                clothing = "a leather apron over plain linen, both stained",
                signatureEquipment = listOf("a case of needles and a bottle of grain spirit"),
            ),
            personality = "Quiet, stubborn, asks no questions about how a wound happened.",
            desires = "To keep the door open.",
            fears = "Being made to choose who lives.",
            skills = listOf("surgery", "herbs and poisons", "staying calm", "keeping secrets"),
            weaknesses = listOf("no violence in him", "owes favours to dangerous people"),
            background = "Army surgeon, then a back-room practice nobody official knows about.",
            goals = listOf("Keep the practice supplied through the winter"),
            secrets = listOf("He has treated two men the watch is hanged for killing."),
            startingCurrency = 28,
        ),
        CharacterTemplate(
            id = "heir",
            name = "Casimir Vell",
            age = 22,
            gender = "man",
            tagline = "Inherited a name worth more than the estate attached to it.",
            appearance = Appearance(
                summary = "Slim, well-groomed, dark curls, clothes a season out of fashion and carefully maintained.",
                face = "fine-boned, a small mole beneath the right eye",
                skin = "brown, unweathered",
                hair = "black curls, well cut",
                eyes = "dark",
                build = "slim, untrained",
                notableMarks = listOf("a small mole beneath the right eye"),
                clothing = "a good coat one season out of fashion, immaculately kept",
                signatureEquipment = listOf("a signet ring", "a duelling pistol he has never fired"),
            ),
            personality = "Polite, watchful, quietly furious about the position he has been left in.",
            desires = "To keep the family standing without selling the last of it.",
            fears = "Being laughed at.",
            skills = listOf("court manners", "reading contracts", "riding", "names and faces"),
            weaknesses = listOf("no practical skills", "recognisable everywhere"),
            background = "His father died owing everyone, and told nobody.",
            goals = listOf("Find out what his father actually signed away"),
            secrets = listOf("He has already sold two of the family's paintings."),
            startingCurrency = 200,
        ),
        CharacterTemplate(
            id = "survivor",
            name = "Tam",
            age = 19,
            gender = "nonbinary",
            tagline = "Something in their blood frightens people who know what to look for.",
            appearance = Appearance(
                summary = "Short, underfed, shaved head, pale eyes that do not blink often. Fine dark lines under the skin of both forearms.",
                face = "sharp cheekbones, pale unblinking eyes",
                skin = "grey-pale, dark tracery visible beneath the forearms",
                hair = "shaved to stubble",
                eyes = "almost colourless",
                build = "short and underfed",
                notableMarks = listOf("dark branching lines under the skin of both forearms"),
                clothing = "layered castoffs, everything too big",
                signatureEquipment = listOf("a length of iron chain wrapped at the wrist"),
            ),
            personality = "Watchful, blunt, does not perform gratitude.",
            desires = "To find out what was done to them, and by whom.",
            fears = "That it is getting worse.",
            skills = listOf("going unnoticed", "running", "enduring", "whatever it is their blood does"),
            weaknesses = listOf("no education", "the marks are spreading", "hunted by people who pay well"),
            background = "Street-raised. Woke up one morning three years ago with the marks and no memory of the night before.",
            goals = listOf("Find the physician whose mark is burned into their shoulder"),
            secrets = listOf("They have already killed someone with it, by accident."),
            startingCurrency = 3,
        ),
    )

    fun byId(id: String) = ALL.firstOrNull { it.id == id }
}
